---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Prepare filebeat config file
  template:
    src: filebeat-config.yml.j2
    dest: /etc/filebeat/filebeat.yml
    backup: true
  notify:
    - restart filebeat

- name: Copy filebeat modules
  template:
    src: "{{ filebeat_modules_sourcedir }}/{{ item }}"
    dest: /etc/filebeat/modules.d/{{ item | basename | regex_replace('\.j2','') }}
    backup: true
  with_items:
    - "{{ filebeat_modules }}"
  notify:
    - restart filebeat


- name: Start and enable filebeat service
  service: name=filebeat enabled=yes state=started
